<!DOCTYPE html>
<html lang="en">

<head>
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<meta name="keywords" content="MediaCenter, Template, eCommerce">
<meta name="robots" content="all">
<title>Marazzo premium HTML5 & CSS3 Template</title>

<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href="<?php echo $css; ?>bootstrap.min.css">

<!-- Customizable CSS -->

<link rel="stylesheet" href="<?php echo $css; ?>blue.css">
<link rel="stylesheet" href="<?php echo $css; ?>owl.carousel.css">
<link rel="stylesheet" href="<?php echo $css; ?>owl.transitions.css">
<link rel="stylesheet" href="<?php echo $css; ?>animate.min.css">
<link rel="stylesheet" href="<?php echo $css; ?>rateit.css">
<link rel="stylesheet" href="<?php echo $css; ?>bootstrap-select.min.css">

<!-- Icons/Glyphs -->
<link rel="stylesheet" href="<?php echo $css; ?>font-awesome.css">
<?php
$i1 = rand(1,9); $i2 =$i1 + 1; $i3 = $i1 - 1 ; $i4 = $i1;
 $v = $i1.'.'.$i2.'.'.$i3.'.'.$i4; ?>


<!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Barlow:200,300,300i,400,400i,500,500i,600,700,800" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,600italic,700,700italic,800' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="<?php echo $css; ?>main.css?v=<?php echo $v ?>">
</head>
<body class="cnt-home">
<!-- ============================================== HEADER ============================================== -->
